# Generated by Django 4.1.9 on 2023-06-15 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAddress',
            fields=[
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DateCreatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('UnitNumber', models.CharField(max_length=255)),
                ('StreetNumber', models.CharField(max_length=255)),
                ('AddressLineOne', models.CharField(max_length=255)),
                ('AddressLineTwo', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=255, null=True)),
                ('Region', models.CharField(blank=True, max_length=255, null=True)),
                ('PostalCode', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='AppCountry',
            fields=[
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DateCreatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('CountryName', django_countries.fields.CountryField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['-CountryName'],
            },
        ),
        migrations.CreateModel(
            name='AppUserAddress',
            fields=[
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DateCreatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('AddressId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Address.appaddress')),
                ('AppUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.appuser')),
            ],
            options={
                'verbose_name': 'UserAddress',
                'verbose_name_plural': 'UserAddresses',
            },
        ),
        migrations.AddField(
            model_name='appaddress',
            name='CountryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Address.appcountry'),
        ),
    ]
