# Generated by Django 4.1.9 on 2023-06-15 20:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Posts', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppReactionType',
            fields=[
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DateCreatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ReactionType', models.TextField(unique=True)),
                ('ReactionEmoji', models.URLField()),
            ],
            options={
                'verbose_name': 'ReactionType',
                'verbose_name_plural': 'ReactionsType',
            },
        ),
        migrations.CreateModel(
            name='AppReaction',
            fields=[
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DateCreatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('PostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.apppost')),
                ('ReactionTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votes.appreactiontype')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.appuser')),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'unique_together': {('UserId', 'PostId')},
            },
        ),
        migrations.CreateModel(
            name='AppComment',
            fields=[
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DateCreatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Comment', models.TextField()),
                ('CommentRepliedToId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Votes.appcomment')),
                ('PostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.apppost')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.appuser')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'unique_together': {('UserId', 'PostId')},
            },
        ),
    ]
